.github/workflows/release.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/722
=> Allowing for a non specific GCR key to be provided.

.github/workflows/release.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/772
=> Attempt to fix release action

.github/workflows/release.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/772
=> Fixing release workflow.

.github/workflows/release.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/859
=> Attempting to configure convictional/trigger-workflow-and-wait.

.github/workflows/build-mod.yml
Details:
- https://ksoclabs.slack.com/archives/C03AANS1KDL/p1664981864293999?thread_ts=1664978806.858259&cid=C03AANS1KDL
=> Add action for module build step. Use race checker

.github/workflows/scan-codeql.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/1355
=> Add new action for scan-codeql

.github/workflows/release.yml
- Towards https://github.com/ksoc-private/engineering-issues/issues/1052
=> Use $GITHUB_OUTPUT in place of ::set-output

.github/workflows/rdme-openapi.yml
Towards:
- https://github.com/ksoc-private/engineering-issues/issues/1559
=> Create readme.com GH action

.github/workflows/scan-codeql.yml
Towards https://github.com/ksoc-private/engineering-issues/issues/1355
=> Needs to be triggered by workflow call

.github/workflows/rdme-openapi.yml
Towards:
- https://github.com/ksoc-private/engineering-issues/issues/1600
=> Add missing quotes

.github/workflows/rdme-openapi.yml
Towards:
- https://github.com/ksoc-private/engineering-issues/issues/1600
=> Fix jq params

.github/workflows/build-mod.yml
Towards:
- https://github.com/ksoc-private/engineering-issues/issues/1673.
=> Update build-mod Go version to 1.20

CODEOWNERS
Towards https://github.com/ksoc-private/engineering-issues/issues/1687
=> Aligning CODEOWNERS.

.github/workflows/build-images-public.yaml
Simplify docker build by removing version script dependency
=> Simplify docker build by removing version script dependency

.github/workflows/build-images-public.yaml
Add release phase in build-images-public
=> Add release phase in build-images-public

.github/workflows/golangci-lint.yml
=> ENG-2010: Bump Linter Version

.github/workflows/build-marketplace-ecr-images.yaml, .github/workflows/build-mod.yml, .github/workflows/build-public-ecr-images.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, .github/workflows/scan-codeql.yml, .github/workflows/swagger.yml, .github/workflows/test.yml
Towards: https://linear.app/rad-security/issue/ENG-2109/remove-ksoc-name-and-replace-it-with-rad-in-all-plugins
=> Bump go version, fix checkout

.github/workflows/golangci-lint.yml, .github/workflows/goreleaser_release.yml, .github/workflows/release.yml, .github/workflows/test.yml
Add config parameter to missed workflow (didn't realise we have 2 release workflow).
This change also updates the newly added input names to be more descriptive.
=> ENG-2383: Add Sum File Cache Key to Release Workflow

marketplace-ecr-auth/action.yml, public-ecr-auth/action.yaml
Towards ENG-2294
Adds Composite Github Actions to use Public ECR Registries and Marketplace ECR Registries.
=> Add public ecr action

.github/workflows/build-mod.yml, .github/workflows/golangci-lint.yml, .github/workflows/goreleaser_release.yml, .github/workflows/release.yml, .github/workflows/scan-codeql.yml, .github/workflows/swagger.yml, .github/workflows/test.yml, marketplace-ecr-auth/action.yml, private-ecr-auth/action.yml, public-ecr-auth/action.yaml
=> Bump go version

.github/workflows/golangci-lint-v2.yml
Towards: https://linear.app/rad-security/issue/ENG-2764/improvefix-public-api-docs
=> Add golangci-lint v2 action
